// Data source. Defaults to static JSON files baked into the build by
// scripts/export_static_data.py. Set NEXT_PUBLIC_API_URL to point at a
// live FastAPI backend if you're iterating on the API itself.
//
// Static layout:
//   /data/memorial.json
//   /data/cases/{runId}/{caseIndex}.json
const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "";
const USE_STATIC = !API_BASE;

export interface DeathSummary {
  case_index: number;
  run_id: string;
  victim_name: string | null;
  victim_name_he: string | null;
  victim_name_ar: string | null;
  victim_name_en?: string | null;
  // List-projection of the post-merge transliterations. Same shape as
  // CaseDetail.name_transliterations below; redeclared inline to keep
  // this type self-contained for the homepage map markers.
  name_transliterations?: Array<{
    value: string;
    target_script: "ar" | "he" | "en";
    source_script: "ar" | "he" | "en";
    method: "dictionary" | "rule_based";
    source_value?: string | null;
  }>;
  victim_age: number | null;
  incident_date: string | null;
  confidence_score: number | null;
}

export interface Locality {
  city: string;
  city_he: string | null;
  city_ar: string | null;
  lat: number;
  lng: number;
  death_count: number;
  most_recent_incident_date: string | null;
  deaths: DeathSummary[];
}

export interface MemorialResponse {
  run_id: string | null;
  year_range: { from: number | null; to: number | null };
  total_deaths: number;
  documented_deaths: number;
  under_40_pct: number;
  unresolved_count: number;
  year_counts: Record<string, number>;
  localities: Locality[];
}

export interface Source {
  url: string;
  domain?: string | null;
  source_name?: string | null;
  actual_publisher?: string | null;
  discovery_source?: string | null;
  language?: string | null;
  published_at: string | null;
  title?: string | null;
  role?: string | null;
  tier?: number | null;
}

export interface MediaItem {
  primary_url: string;
  type: string | null;
  is_evidence: boolean;
  caption: string | null;
  // Fields populated by the media pipeline that the UI uses for
  // attribution and rendering. Optional because legacy exports
  // (pre-media-pipeline) only carried primary_url + caption.
  alt_text?: string | null;
  width?: number | null;
  height?: number | null;
  source_article_urls?: string[];
  mirror_urls?: string[];
  classifier_tier?: string | null;
  confidence?: number | null;
}

export interface Transliteration {
  value: string;
  target_script: "ar" | "he" | "en";
  source_script: "ar" | "he" | "en";
  method: "dictionary" | "rule_based";
  source_value: string | null;
}

export interface CaseDetail {
  case_index: number;
  run_id: string;
  victim_name: string | null;
  victim_name_he: string | null;
  victim_name_ar: string | null;
  victim_name_en: string | null;
  // Inferred name forms generated by the post-merge transliteration
  // stage. Source-of-truth ``victim_name_*`` fields are reserved for
  // source-attested values; anything here was produced by the
  // deterministic transliterator and should be rendered with a
  // visible "inferred" cue.
  name_transliterations?: Transliteration[];
  victim_age: number | null;
  victim_gender: string | null;
  incident_date: string | null;
  death_date: string | null;
  city: string | null;
  // Gazetteer-normalized city record with all three scripts +
  // district/region/lat/lng. Null when the extracted city wasn't in
  // the gazetteer — UI must fall back to the raw ``city`` field.
  city_normalized?: {
    name_ar?: string | null;
    name_he?: string | null;
    name_en?: string | null;
    district?: string | null;
    region?: string | null;
    lat?: number | null;
    lng?: number | null;
  } | null;
  neighborhood: string | null;
  district: string | null;
  weapon_type: string | null;
  suspect_status: string | null;
  legal_status: string | null;
  case_narrative: string | null;
  // Language-specific narratives produced by the narrate pipeline stage
  // (2-3 sentences each, generated by Gemini from merged structured
  // fields + source bodies). UI prefers these over the legacy single
  // ``case_narrative`` string; ``case_narrative`` is kept for back-compat.
  case_narrative_ar?: string | null;
  case_narrative_he?: string | null;
  case_narrative_en?: string | null;
  sources: Source[];
  media_evidence: MediaItem[];
  conflicts?: Record<string, unknown> | null;
  conflict_map?: Record<string, unknown> | null;
}

export async function fetchMemorial(): Promise<MemorialResponse> {
  const url = USE_STATIC ? "/data/memorial.json" : `${API_BASE}/api/memorial`;
  const res = await fetch(url, { cache: "no-store" });
  if (!res.ok) throw new Error(`fetch error ${res.status} (${url})`);
  return res.json();
}

export async function fetchCase(runId: string, caseIndex: number): Promise<CaseDetail> {
  const url = USE_STATIC
    ? `/data/cases/${runId}/${caseIndex}.json`
    : `${API_BASE}/api/cases/${runId}/${caseIndex}`;
  const res = await fetch(url, { cache: "no-store" });
  if (!res.ok) throw new Error(`fetch error ${res.status} (${url})`);
  return res.json();
}
